### ISSUE TITLE
Failed opening archive: Error: Encrypted content has been tampered with

### ISSUE THREAD

**Issue by benjamincharity** [himynameisdave/git-labelmaker#69]
Recently updated `git-labelmaker` and am now getting this error frequently. I've recreated the token multiple times now which gets it working for a few commands, but I see this message again within minutes.

To reproduce:

- set your token
- run commands (I can usually run a few in quick succession before seeing this error)
- `$ git-labelmaker`
- choose: use saved token
- type your master password
- See error: `Failed opening archive: Error: Encrypted content has been tampered with`

---

- git-labelmaker@0.8.1
- Sierra 10.12.1
- zsh 5.2

---

Not sure if this is a bug or a setup issue on my end. Hoping someone might point me in the right direction. (fwiw `git-labelmaker` has worked perfectly for me the better part of this year - saved me SO much time 💥 )

---

Ninja edit: It appears that if I `ctrl+c` when shown that error and restart the process, it no longer thinks the content has been tampered with.

**Comment by Jameskmonger** [comment]
@perry-mitchell

**Comment by perry-mitchell** [comment]
Hi @benjamincharity - The underlying encryption engine outputs that message when it can't properly decrypt the content. The message is a bit misleading, though it basically means that your password was not correct and the HMAC authentication on the data was not matched (your Git credentials were not retrievable in this case).

Could you possibly retry with a VERY simple password? Like "abc" or something? Could it be possible that you miss-typed the password due to it being very complicated or using special chars?

**Comment by benjamincharity** [comment]
Interesting. That actually does make sense.. I could have easily mistyped it which would be why it seemed to work when I `ctrl+c`'d and tried again. Just a confusing error message.

Thanks for the clarity! (and the useful project!)

**Comment by perry-mitchell** [comment]
@benjamincharity No problem! The message **is** unclear, and we're working to formulate better failure messages.
